spring.application.name=syncboard
spring.datasource.url=jdbc:mysql://localhost:3306/syncboard_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
